# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000  
    nodePort: 31443
  selector:
    app: web-service

---
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-service
  template:
    metadata:
      labels:
        app: web-service
    spec:
      containers:
      - name: web-service
        image: web-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000  
        readinessProbe:
          httpGet:
            path: /health
            port: 5000  
          initialDelaySeconds: 5
          periodSeconds: 10